{
  "2014-09-26"=>[
    {
      : title=>"ADaM Controlled Terminology Package 19 Effective 2014-09-26",
      : date=>"2014-09-26",
      : package=>19,
      : href=>"/mdr/ct/packages/adamct-2014-09-26"
    },
    {
      : title=>"CDASH Controlled Terminology Package 19 Effective 2014-09-26",
      : date=>"2014-09-26",
      : package=>19,
      : href=>"/mdr/ct/packages/cdashct-2014-09-26"
    },
    {
      : title=>"QS-FT Controlled Terminology Package 19 Effective 2014-09-26",
      : date=>"2014-09-26",
      : package=>19,
      : href=>"/mdr/ct/packages/qs-ftct-2014-09-26"
    },
    {
      : title=>"SDTM Controlled Terminology Package 19 Effective 2014-09-26",
      : date=>"2014-09-26",
      : package=>19,
      : href=>"/mdr/ct/packages/sdtmct-2014-09-26"
    },
    {
      : title=>"SEND Controlled Terminology Package 19 Effective 2014-09-26",
      : date=>"2014-09-26",
      : package=>19,
      : href=>"/mdr/ct/packages/sendct-2014-09-26"
    }
  ],
  "2014-12-19"=>[
    {
      : title=>"COA Controlled Terminology Package 20 Effective 2014-12-19",
      : date=>"2014-12-19",
      : package=>20,
      : href=>"/mdr/ct/packages/coact-2014-12-19"
    },
    {
      : title=>"SDTM Controlled Terminology Package 20 Effective 2014-12-19",
      : date=>"2014-12-19",
      : package=>20,
      : href=>"/mdr/ct/packages/sdtmct-2014-12-19"
    },
    {
      : title=>"SEND Controlled Terminology Package 20 Effective 2014-12-19",
      : date=>"2014-12-19",
      : package=>20,
      : href=>"/mdr/ct/packages/sendct-2014-12-19"
    }
  ],
  "2015-03-27"=>[
    {
      : title=>"CDASH Controlled Terminology Package 21 Effective 2015-03-27",
      : date=>"2015-03-27",
      : package=>21,
      : href=>"/mdr/ct/packages/cdashct-2015-03-27"
    },
    {
      : title=>"COA Controlled Terminology Package 21 Effective 2015-03-27",
      : date=>"2015-03-27",
      : package=>21,
      : href=>"/mdr/ct/packages/coact-2015-03-27"
    },
    {
      : title=>"SDTM Controlled Terminology Package 21 Effective 2015-03-27",
      : date=>"2015-03-27",
      : package=>21,
      : href=>"/mdr/ct/packages/sdtmct-2015-03-27"
    },
    {
      : title=>"SEND Controlled Terminology Package 21 Effective 2015-03-27",
      : date=>"2015-03-27",
      : package=>21,
      : href=>"/mdr/ct/packages/sendct-2015-03-27"
    }
  ],
  "2015-06-26"=>[
    {
      : title=>"QRS Controlled Terminology Package 22 Effective 2015-06-26",
      : date=>"2015-06-26",
      : package=>22,
      : href=>"/mdr/ct/packages/qrsct-2015-06-26"
    },
    {
      : title=>"SDTM Controlled Terminology Package 22 Effective 2015-06-26",
      : date=>"2015-06-26",
      : package=>22,
      : href=>"/mdr/ct/packages/sdtmct-2015-06-26"
    },
    {
      : title=>"SEND Controlled Terminology Package 22 Effective 2015-06-26",
      : date=>"2015-06-26",
      : package=>22,
      : href=>"/mdr/ct/packages/sendct-2015-06-26"
    }
  ],
  "2015-09-25"=>[
    {
      : title=>"QRS Controlled Terminology Package 23 Effective 2015-09-25",
      : date=>"2015-09-25",
      : package=>23,
      : href=>"/mdr/ct/packages/qrsct-2015-09-25"
    },
    {
      : title=>"SDTM Controlled Terminology Package 23 Effective 2015-09-25",
      : date=>"2015-09-25",
      : package=>23,
      : href=>"/mdr/ct/packages/sdtmct-2015-09-25"
    },
    {
      : title=>"SEND Controlled Terminology Package 23 Effective 2015-09-25",
      : date=>"2015-09-25",
      : package=>23,
      : href=>"/mdr/ct/packages/sendct-2015-09-25"
    }
  ],
  "2015-12-18"=>[
    {
      : title=>"ADaM Controlled Terminology Package 24 Effective 2015-12-18",
      : date=>"2015-12-18",
      : package=>24,
      : href=>"/mdr/ct/packages/adamct-2015-12-18"
    },
    {
      : title=>"SDTM Controlled Terminology Package 24 Effective 2015-12-18",
      : date=>"2015-12-18",
      : package=>24,
      : href=>"/mdr/ct/packages/sdtmct-2015-12-18"
    },
    {
      : title=>"SEND Controlled Terminology Package 24 Effective 2015-12-18",
      : date=>"2015-12-18",
      : package=>24,
      : href=>"/mdr/ct/packages/sendct-2015-12-18"
    }
  ],
  "2016-03-25"=>[
    {
      : title=>"ADaM Controlled Terminology Package 25 Effective 2016-03-25",
      : date=>"2016-03-25",
      : package=>25,
      : href=>"/mdr/ct/packages/adamct-2016-03-25"
    },
    {
      : title=>"CDASH Controlled Terminology Package 25 Effective 2016-03-25",
      : date=>"2016-03-25",
      : package=>25,
      : href=>"/mdr/ct/packages/cdashct-2016-03-25"
    },
    {
      : title=>"SDTM Controlled Terminology Package 25 Effective 2016-03-25",
      : date=>"2016-03-25",
      : package=>25,
      : href=>"/mdr/ct/packages/sdtmct-2016-03-25"
    },
    {
      : title=>"SEND Controlled Terminology Package 25 Effective 2016-03-25",
      : date=>"2016-03-25",
      : package=>25,
      : href=>"/mdr/ct/packages/sendct-2016-03-25"
    }
  ],
  "2016-06-24"=>[
    {
      : title=>"SDTM Controlled Terminology Package 26 Effective 2016-06-24",
      : date=>"2016-06-24",
      : package=>26,
      : href=>"/mdr/ct/packages/sdtmct-2016-06-24"
    },
    {
      : title=>"SEND Controlled Terminology Package 26 Effective 2016-06-24",
      : date=>"2016-06-24",
      : package=>26,
      : href=>"/mdr/ct/packages/sendct-2016-06-24"
    }
  ],
  "2016-09-30"=>[
    {
      : title=>"ADaM Controlled Terminology Package 27 Effective 2016-09-30",
      : date=>"2016-09-30",
      : package=>27,
      : href=>"/mdr/ct/packages/adamct-2016-09-30"
    },
    {
      : title=>"CDASH Controlled Terminology Package 27 Effective 2016-09-30",
      : date=>"2016-09-30",
      : package=>27,
      : href=>"/mdr/ct/packages/cdashct-2016-09-30"
    },
    {
      : title=>"SDTM Controlled Terminology Package 27 Effective 2016-09-30",
      : date=>"2016-09-30",
      : package=>27,
      : href=>"/mdr/ct/packages/sdtmct-2016-09-30"
    },
    {
      : title=>"SEND Controlled Terminology Package 27 Effective 2016-09-30",
      : date=>"2016-09-30",
      : package=>27,
      : href=>"/mdr/ct/packages/sendct-2016-09-30"
    }
  ],
  "2016-12-16"=>[
    {
      : title=>"ADaM Controlled Terminology Package 28 Effective 2016-12-16",
      : date=>"2016-12-16",
      : package=>28,
      : href=>"/mdr/ct/packages/adamct-2016-12-16"
    },
    {
      : title=>"CDASH Controlled Terminology Package 28 Effective 2016-12-16",
      : date=>"2016-12-16",
      : package=>28,
      : href=>"/mdr/ct/packages/cdashct-2016-12-16"
    },
    {
      : title=>"SDTM Controlled Terminology Package 28 Effective 2016-12-16",
      : date=>"2016-12-16",
      : package=>28,
      : href=>"/mdr/ct/packages/sdtmct-2016-12-16"
    },
    {
      : title=>"SEND Controlled Terminology Package 28 Effective 2016-12-16",
      : date=>"2016-12-16",
      : package=>28,
      : href=>"/mdr/ct/packages/sendct-2016-12-16"
    }
  ],
  "2017-03-31"=>[
    {
      : title=>"ADaM Controlled Terminology Package 29 Effective 2017-03-31",
      : date=>"2017-03-31",
      : package=>29,
      : href=>"/mdr/ct/packages/adamct-2017-03-31"
    },
    {
      : title=>"PROTOCOL Controlled Terminology Package 29 Effective 2017-03-31",
      : date=>"2017-03-31",
      : package=>29,
      : href=>"/mdr/ct/packages/protocolct-2017-03-31"
    },
    {
      : title=>"SDTM Controlled Terminology Package 29 Effective 2017-03-31",
      : date=>"2017-03-31",
      : package=>29,
      : href=>"/mdr/ct/packages/sdtmct-2017-03-31"
    },
    {
      : title=>"SEND Controlled Terminology Package 29 Effective 2017-03-31",
      : date=>"2017-03-31",
      : package=>29,
      : href=>"/mdr/ct/packages/sendct-2017-03-31"
    }
  ],
  "2017-06-30"=>[
    {
      : title=>"PROTOCOL Controlled Terminology Package 30 Effective 2017-06-30",
      : date=>"2017-06-30",
      : package=>30,
      : href=>"/mdr/ct/packages/protocolct-2017-06-30"
    },
    {
      : title=>"SDTM Controlled Terminology Package 30 Effective 2017-06-30",
      : date=>"2017-06-30",
      : package=>30,
      : href=>"/mdr/ct/packages/sdtmct-2017-06-30"
    },
    {
      : title=>"SEND Controlled Terminology Package 30 Effective 2017-06-30",
      : date=>"2017-06-30",
      : package=>30,
      : href=>"/mdr/ct/packages/sendct-2017-06-30"
    }
  ],
  "2017-09-29"=>[
    {
      : title=>"ADaM Controlled Terminology Package 31 Effective 2017-09-29",
      : date=>"2017-09-29",
      : package=>31,
      : href=>"/mdr/ct/packages/adamct-2017-09-29"
    },
    {
      : title=>"CDASH Controlled Terminology Package 31 Effective 2017-09-29",
      : date=>"2017-09-29",
      : package=>31,
      : href=>"/mdr/ct/packages/cdashct-2017-09-29"
    },
    {
      : title=>"PROTOCOL Controlled Terminology Package 31 Effective 2017-09-29",
      : date=>"2017-09-29",
      : package=>31,
      : href=>"/mdr/ct/packages/protocolct-2017-09-29"
    },
    {
      : title=>"SDTM Controlled Terminology Package 31 Effective 2017-09-29",
      : date=>"2017-09-29",
      : package=>31,
      : href=>"/mdr/ct/packages/sdtmct-2017-09-29"
    },
    {
      : title=>"SEND Controlled Terminology Package 31 Effective 2017-09-29",
      : date=>"2017-09-29",
      : package=>31,
      : href=>"/mdr/ct/packages/sendct-2017-09-29"
    }
  ],
  "2017-12-22"=>[
    {
      : title=>"SDTM Controlled Terminology Package 32 Effective 2017-12-22",
      : date=>"2017-12-22",
      : package=>32,
      : href=>"/mdr/ct/packages/sdtmct-2017-12-22"
    },
    {
      : title=>"SEND Controlled Terminology Package 32 Effective 2017-12-22",
      : date=>"2017-12-22",
      : package=>32,
      : href=>"/mdr/ct/packages/sendct-2017-12-22"
    }
  ],
  "2018-03-30"=>[
    {
      : title=>"CDASH Controlled Terminology Package 33 Effective 2018-03-30",
      : date=>"2018-03-30",
      : package=>33,
      : href=>"/mdr/ct/packages/cdashct-2018-03-30"
    },
    {
      : title=>"PROTOCOL Controlled Terminology Package 33 Effective 2018-03-30",
      : date=>"2018-03-30",
      : package=>33,
      : href=>"/mdr/ct/packages/protocolct-2018-03-30"
    },
    {
      : title=>"SDTM Controlled Terminology Package 33 Effective 2018-03-30",
      : date=>"2018-03-30",
      : package=>33,
      : href=>"/mdr/ct/packages/sdtmct-2018-03-30"
    },
    {
      : title=>"SEND Controlled Terminology Package 33 Effective 2018-03-30",
      : date=>"2018-03-30",
      : package=>33,
      : href=>"/mdr/ct/packages/sendct-2018-03-30"
    }
  ],
  "2018-06-29"=>[
    {
      : title=>"CDASH Controlled Terminology Package 34 Effective 2018-06-29",
      : date=>"2018-06-29",
      : package=>34,
      : href=>"/mdr/ct/packages/cdashct-2018-06-29"
    },
    {
      : title=>"PROTOCOL Controlled Terminology Package 34 Effective 2018-06-29",
      : date=>"2018-06-29",
      : package=>34,
      : href=>"/mdr/ct/packages/protocolct-2018-06-29"
    },
    {
      : title=>"SDTM Controlled Terminology Package 34 Effective 2018-06-29",
      : date=>"2018-06-29",
      : package=>34,
      : href=>"/mdr/ct/packages/sdtmct-2018-06-29"
    },
    {
      : title=>"SEND Controlled Terminology Package 34 Effective 2018-06-29",
      : date=>"2018-06-29",
      : package=>34,
      : href=>"/mdr/ct/packages/sendct-2018-06-29"
    }
  ],
  "2018-09-28"=>[
    {
      : title=>"CDASH Controlled Terminology Package 35 Effective 2018-09-28",
      : date=>"2018-09-28",
      : package=>35,
      : href=>"/mdr/ct/packages/cdashct-2018-09-28"
    },
    {
      : title=>"PROTOCOL Controlled Terminology Package 35 Effective 2018-09-28",
      : date=>"2018-09-28",
      : package=>35,
      : href=>"/mdr/ct/packages/protocolct-2018-09-28"
    },
    {
      : title=>"SDTM Controlled Terminology Package 35 Effective 2018-09-28",
      : date=>"2018-09-28",
      : package=>35,
      : href=>"/mdr/ct/packages/sdtmct-2018-09-28"
    },
    {
      : title=>"SEND Controlled Terminology Package 35 Effective 2018-09-28",
      : date=>"2018-09-28",
      : package=>35,
      : href=>"/mdr/ct/packages/sendct-2018-09-28"
    }
  ],
  "2018-12-21"=>[
    {
      : title=>"ADaM Controlled Terminology Package 36 Effective 2018-12-21",
      : date=>"2018-12-21",
      : package=>36,
      : href=>"/mdr/ct/packages/adamct-2018-12-21"
    },
    {
      : title=>"CDASH Controlled Terminology Package 36 Effective 2018-12-21",
      : date=>"2018-12-21",
      : package=>36,
      : href=>"/mdr/ct/packages/cdashct-2018-12-21"
    },
    {
      : title=>"SDTM Controlled Terminology Package 36 Effective 2018-12-21",
      : date=>"2018-12-21",
      : package=>36,
      : href=>"/mdr/ct/packages/sdtmct-2018-12-21"
    },
    {
      : title=>"SEND Controlled Terminology Package 36 Effective 2018-12-21",
      : date=>"2018-12-21",
      : package=>36,
      : href=>"/mdr/ct/packages/sendct-2018-12-21"
    }
  ],
  "2019-03-29"=>[
    {
      : title=>"ADaM Controlled Terminology Package 37 Effective 2019-03-29",
      : date=>"2019-03-29",
      : package=>37,
      : href=>"/mdr/ct/packages/adamct-2019-03-29"
    },
    {
      : title=>"CDASH Controlled Terminology Package 37 Effective 2019-03-29",
      : date=>"2019-03-29",
      : package=>37,
      : href=>"/mdr/ct/packages/cdashct-2019-03-29"
    },
    {
      : title=>"PROTOCOL Controlled Terminology Package 37 Effective 2019-03-29",
      : date=>"2019-03-29",
      : package=>37,
      : href=>"/mdr/ct/packages/protocolct-2019-03-29"
    },
    {
      : title=>"SDTM Controlled Terminology Package 37 Effective 2019-03-29",
      : date=>"2019-03-29",
      : package=>37,
      : href=>"/mdr/ct/packages/sdtmct-2019-03-29"
    },
    {
      : title=>"SEND Controlled Terminology Package 37 Effective 2019-03-29",
      : date=>"2019-03-29",
      : package=>37,
      : href=>"/mdr/ct/packages/sendct-2019-03-29"
    }
  ],
  "2019-06-28"=>[
    {
      : title=>"CDASH Controlled Terminology Package 38 Effective 2019-06-28",
      : date=>"2019-06-28",
      : package=>38,
      : href=>"/mdr/ct/packages/cdashct-2019-06-28"
    },
    {
      : title=>"PROTOCOL Controlled Terminology Package 38 Effective 2019-06-28",
      : date=>"2019-06-28",
      : package=>38,
      : href=>"/mdr/ct/packages/protocolct-2019-06-28"
    },
    {
      : title=>"SDTM Controlled Terminology Package 38 Effective 2019-06-28",
      : date=>"2019-06-28",
      : package=>38,
      : href=>"/mdr/ct/packages/sdtmct-2019-06-28"
    },
    {
      : title=>"SEND Controlled Terminology Package 38 Effective 2019-06-28",
      : date=>"2019-06-28",
      : package=>38,
      : href=>"/mdr/ct/packages/sendct-2019-06-28"
    }
  ],
  "2019-09-27"=>[
    {
      : title=>"PROTOCOL Controlled Terminology Package 39 Effective 2019-09-27",
      : date=>"2019-09-27",
      : package=>39,
      : href=>"/mdr/ct/packages/protocolct-2019-09-27"
    },
    {
      : title=>"SDTM Controlled Terminology Package 39 Effective 2019-09-27",
      : date=>"2019-09-27",
      : package=>39,
      : href=>"/mdr/ct/packages/sdtmct-2019-09-27"
    },
    {
      : title=>"SEND Controlled Terminology Package 39 Effective 2019-09-27",
      : date=>"2019-09-27",
      : package=>39,
      : href=>"/mdr/ct/packages/sendct-2019-09-27"
    }
  ]
}