bin/rspec spec/models/concerns/sdtm_excel_spec.rb 
bin/rspec spec/models/sdtm_model_classification_spec.rb
bin/rspec spec/models/sdtm_model_compliance_spec.rb
bin/rspec spec/models/sdtm_model_datatype_spec.rb
bin/rspec spec/models/sdtm_model/variable_spec.rb 
bin/rspec spec/models/sdtm_model_spec.rb 
bin/rspec spec/models/sdtm_model_domain/variable_spec.rb 
bin/rspec spec/models/sdtm_model_domain_spec.rb 
bin/rspec spec/models/sdtm_ig_domain/variable_spec.rb 
bin/rspec spec/models/sdtm_ig_domain_spec.rb 
bin/rspec spec/models/sdtm_ig_spec.rb 
