defaults: &defaults
  DefinedObservation.nameCode.CD.code: "--TESTCD"
  DefinedObservation.nameCode.CD.originalText.ED.value: "--TEST"
  DefinedActivity.categoryCode.CD: "--CAT"
  DefinedActivity.subcategoryCode.CD: "--SCAT"
  PerformedObservationResult.result.PQR.value: "--ORRES"
  PerformedClinicalResult.value.PQR.value: "--ORRES"
  PerformedClinicalResult.value.CD.code: "--ORRES"
  PerformedClinicalResult.value.PQR.code: "--ORRESU"
  PerformedClinicalResult.value.ANY: "--STRESC"
  PerformedObservation.bodyPositionCode.CD.code: "--POS"
  PerformedObservationResult.value.ANY.units: "--ORRESU"
  PerformedObservationResult.result.PQR.code: "--ORRESU"
  PerformedObservationResult.value.ANY: "--STRESN"
  PerformedObservationResult.value.CD.code: "--REL"
  PerformedObservationResult2.value.ST.value: "--RELNST"
  PerformedObservationResult3.value.CD.code: "--SCAN"
  PerformedObservationResult4.value.CD.code: "--SDTH"
  ReferenceResult.value.ANY: "--STNRLO"
  PerformedClinicalResult.normalRangeComparisonCode.CD: "--NRIND"
  PerformedObservation.negationIndicator.BL.value: "--STAT"
  PerformedObservation.negationReason.DSET(SC).value: "--REASND"
  Organization.name.DSET(EN.ON): "--NAM"
  DefinedObservation.targetAnatomicSiteCode.CD.code: "--LOC"
  DefinedObservation.nameCode.CD: "--LOINC"
  Biologic.code.CD: "--SPEC"
  Specimen.conditionCode.CD: "--SPCCND"
  PerformedObservation.methodCode.CD.code: "--METHOD"
  PerformedObservationResult.baselineIndicator.BL: "--BLFL"
  PerformedSpecimenCollection.fastingStatusIndicator.BL: "--FAST"
  PerformedClinicalInterpretation.toxicityTermCode.CD: "--TOX"
  PerformedClinicalInterpretation.toxicityGradeCode.CD: "--TOXGR"
  PlannedSubjectActivityGroup.sequenceNumber.INT.NONNEG: "VISITNUM"
  PlannedActivity.studyDayRange.IVL(INT): "VISITDY"
  PerformedObservation.dateRange.IVL_TS_DATETIME.low.TS_DATETIME.value: "--DTC"
  PerformedSpecimenCollection.dateRange.IVL(TS.DATETIME): "--ENDTC"
  PerformedObservation.studyDayRange.IVL(INT): "--DY"
  PlannedContingentOnRelationship: "--ELTM"
  DefinedActivity.nameCode.CD: "--TPTREF"
  PerformedActivity.dateRange.IVL(TS.DATETIME): "--RFTDTC"
  AdverseEvent.value.ST.value: "--TERM"
  AdverseEvent.categoryCode.CD.code: "--CAT"
  AdverseEvent.subcategoryCode.CD.code: "--SCAT"
  AdverseEvent.severityCode.CD.code: "--SEV"
  AdverseEvent.seriousnessCode.CD.code: "--SER"
  AdverseEvent.occurrencepatternCode.CD.code: "--PATT"
  AdverseEvent.hospitalizationRequiredIndicator.BL.value: "--SHOSP"
  AdverseEvent.occuranceDateRange.IVL_TS_DATETIME.low.TS_DATETIME.value: "--STDTC"
  AdverseEvent.occuranceDateRange.IVL_TS_DATETIME.high.TS_DATETIME.value: "--ENDTC"
  AdverseEventActionTaken.typeCode.CD.code: "--ACN"
  AdverseEventActionTaken2.typeCode.CD.code: "--ACNOTH"
  AdverseEventOutcomeResult.value.CD.code: "--OUT"
development:
  <<: *defaults

production: 
  <<: *defaults
  
test: 
  <<: *defaults