defaults: &defaults
  # Default Configuration
  self_registration: false # Self registration enabled
  token_timeout: 300 # Timeout in seconds
  #organization_title: UCB Biosciences, Inc
  #organization_image_file: ucb.jpg
  organization_title: ACME Pharma
  organization_image_file: acme.jpg
  rest_timeout: 5
  cdisc_ct_files: public/results
  # User config
  paper_size:
   - type: enum
     enum_values: A3 A4 Letter
     value: A4
     label: Paper Size

development:
  <<: *defaults
  self_registration: false

production: 
  <<: *defaults
  
test: 
  <<: *defaults
  cdisc_ct_files: public/test
  token_timeout: 5 
