defaults: &defaults
  # System config
  self_registration: false
  organization_title: ACME Pharmaceuticals
  organization_image_file: acme.jpg
  rest_timeout: 5
  # User config
  paper_size:
   - type: enum
     enum_values: A3 A4 Letter
     value: A4
     label: Paper Size

development:
  <<: *defaults
  self_registration: true

production: 
  <<: *defaults
  
test: 
  <<: *defaults
