defaults: &defaults
  # System config
  self_registration: false
  organization_title: UCB Biosciences, Inc
  organization_image_file: ucb.jpg
  rest_timeout: 5
  # User config
  paper_size:
   - type: enum
     enum_values: A3 A4 Letter
     value: A4
     label: Paper Size

development:
  <<: *defaults
  self_registration: false

production: 
  <<: *defaults
  
test: 
  <<: *defaults
