defaults: &defaults
  # General Settings
  self_registration: false # Self registration enabled
  token_timeout: 300 # Timeout in seconds
  rest_timeout: 5 # REST timeout period
  cdisc_ct_files: public/results/  # CDISC CT file directory
  ad_hoc_report_files: public/reports/  # Ad Hoc Reports directory
  max_impact_hops: 3 # Maximum hops for impact assesment
  # User Settings 
  user_settings:
    paper_size: # Paper size settings
      type: enum
      values: 
       - A3
       - A4
       - Letter
      default_value: A4
      label: Paper Size
    table_rows: # Table rows length settings 
      type: coded
      values: 
        '5': 5 
        '10': 10 
        '15': 15
        '25': 25
        '50': 50
        '100': 100
        All: -1
      default_value: 10
      label: Table Rows
    edit_lock_warning: # Time for edit lock warning
      type: coded
      values: 
        '30s': 30 
        '1m': 60 
        '1m 30s': 90 
        '2m': 120
        '3m': 180
        '5m': 300
      default_value: 60
      label: Edit Lock Warning
development:
  <<: *defaults

production: 
  <<: *defaults
  
test: 
  <<: *defaults
  cdisc_ct_files: public/test/
  ad_hoc_report_files: public/test/
  token_timeout: 5 
