defaults: &defaults
  # General Settings
  application_name: "A3ccelerate"
  application_image: "glandon.png"
  self_registration: false # Self registration enabled
  rest_timeout: 20 # REST timeout period
  cdisc_ct_files: public/results/  # CDISC CT file directory
  ad_hoc_report_files: public/reports/  # Ad Hoc Reports directory
  export_files: public/exports/  # Exports directory
  import_files: public/imports/  # Exports directory
  upload_files: public/upload/  # Upload directory
  help_url: "https://www.s-cubed-global.com/products/a3-community-mdr/a3-community-mdr-guides" # Video guides URL for the community version
  max_impact_hops: 3 # Maximum hops for impact assesment
  bridg_path_coded:
   - CD.originalText.ED.value
   - CD.code
   - PQR.code
   - PQR_INT.code
  dashboard_panels:
    terminologies: "Terminologies"
    bct: "Biomedical Concept Templates"
    bcs: "Biomedical Concepts"
    forms: "Forms"
    domains: "Domains"
    stats: "Statistics"
  # User Settings
  user_settings:
    paper_size: # Paper size settings
      type: enum
      values:
       - A3
       - A4
       - Letter
      default_value: A4
      label: Paper Size
      description: The paper size to be used for PDF reports exported by the system.
    table_rows: # Table rows length settings
      type: coded
      values:
        '5': 5
        '10': 10
        '15': 15
        '25': 25
        '50': 50
        '100': 100
        All: -1
      default_value: 10
      label: Table Rows
      description: The number of rows to be used within table displays.
    edit_lock_warning: # Time for edit lock warning
      type: coded
      values:
        '30s': 30
        '1m': 60
        '1m 30s': 90
        '2m': 120
        '3m': 180
        '5m': 300
      default_value: 60
      label: Edit Lock Warning
      description: The time at which a warning will be issued before an edit lock is lost. Half way to the lock being lost a second warning will be issued.
        Times are expressed in minutes and seconds.
    user_name_display: # Display user name in nav bar
      type: enum
      values:
       - 'Yes'
       - 'No'
      default_value: 'Yes'
      label: Display User Name
      description: Display the user name in the top navigation bar.
    user_role_display: # Display user roles in nav bar
      type: enum
      values:
       - 'Yes'
       - 'No'
      default_value: 'Yes'
      label: Display User Roles
      description: Display the user roles in the top navigation bar.
    max_term_display: # Maximum number of terminologies to be displayed
      type: coded
      values:
        '4': 4
        '8': 8
        '12': 12
      default_value: 4
      label: Terminology Versions Displayed
      description: Number of terminologies to be displayed in change tables.
    dashboard_layout:
      type: ordered
      default_value: terminologies, stats
      label: Layout of the Dashboard
      description: Customize this setting in the Dashboard page.


development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
  application_name: "Glandon MDR"
  cdisc_ct_files: public/test/
  ad_hoc_report_files: public/test/
  export_files: public/test/
  import_files: public/test/
  upload_files: public/test/
