defaults: &defaults
  "Thesaurus::ManagedConcept": 
    - "Thesaurus::ManagedConcept"
    - "BiomedicalConceptInstance"
    - "Form"
    - "Thesaurus"
  "BiomedicalConceptInstance":
    - "Form"
    - "SdtmSponsorDomain"
  "SdtmClass":
    - "Form"
    - "SdtmSponsorDomain"
  "Form": []

development:
  <<: *defaults

production: 
  <<: *defaults
  
test: 
  <<: *defaults
  "IMDLayer1":
    - "IMDLayer2"
  "IMDLayer2":
    - "IMDLayer3"
  "IMDLayer3": []
