defaults: &defaults
  "Thesaurus::ManagedConcept": 
    - "Thesaurus::ManagedConcept"
  "BiomedicalConceptInstance":
    - "Thesaurus::ManagedConcept"
  "Form":
    - "BiomedicalConceptInstance"
    - "Thesaurus::ManagedConcept"

development:
  <<: *defaults

production: 
  <<: *defaults
  
test: 
  <<: *defaults