--- 
development:
  dbType: "Fuseki"
  apiKey: ""
  secret: ""
  queryEndpoint: "https://localhost:3030/mdr/query"
  updateEndpoint: "https://localhost:3030/mdr/update"
production: 
  dbType: "Fuseki"
  apiKey: ""
  secret: ""
  queryEndpoint: "https://localhost:3030/mdr/query"
  updateEndpoint: "https://localhost:3030/mdr/update"
test: 
  dbType: "Fuseki"
  apiKey: ""
  secret: ""
  queryEndpoint: "https://localhost:3030/mdr/query"
  updateEndpoint: "https://localhost:3030/mdr/update"