--- 
development:
  dbType: "Fuseki"
  apiKey: ""
  secret: ""
  queryEndpoint: "http://localhost:3030/mdr/query"
  updateEndpoint: "http://localhost:3030/mdr/update"
  fileEndpoint: "http://localhost:3030/mdr/upload"
production: 
  dbType: "Fuseki"
  apiKey: ""
  secret: ""
  queryEndpoint: "http://localhost:3030/mdr/query"
  updateEndpoint: "http://localhost:3030/mdr/update"
  fileEndpoint: "http://localhost:3030/mdr/upload"
test: 
  dbType: "Fuseki"
  apiKey: ""
  secret: ""
  queryEndpoint: "http://localhost:3030/test/query"
  updateEndpoint: "http://localhost:3030/test/update"
  fileEndpoint: "http://localhost:3030/test/upload"