--- 
development:
  dbType: "Fuseki"
  apiKey: ""
  secret: ""
#  queryEndpoint: "http://192.168.2.101:3030/mdr/query"
#  updateEndpoint: "http://192.168.2.101:3030/mdr/update"
#  fileEndpoint: "http://192.168.2.101:3030/mdr/data"
  queryEndpoint: "http://localhost:3030/mdr/query"
  updateEndpoint: "http://localhost:3030/mdr/update"
  fileEndpoint: "http://localhost:3030/mdr/data"
production: 
  dbType: "Fuseki"
  apiKey: ""
  secret: ""
  queryEndpoint: "http://192.168.2.101:3030/mdr/query"
  updateEndpoint: "http://192.168.2.101:3030/mdr/update"
  fileEndpoint: "http://192.168.2.101:3030/mdr/data"
test: 
  dbType: "Fuseki"
  apiKey: ""
  secret: ""
  queryEndpoint: "http://192.168.2.101:3030/mdr/query"
  updateEndpoint: "http://192.168.2.101:3030/mdr/update"
  fileEndpoint: "http://192.168.2.101:3030/mdr/data"