defaults: &defaults
  imports:
    adam_ig:
      title: ADaM IG Import - Excel
      background: true
      description: This facilty allows for the ADaM Implementation Guide to be imported from an MS Excel file.
      link_text: "Import ADaM IG"
      link_path: "/imports/adam_igs/new?imports[file_type]=0"
    form_als:
      title: Form Import - ALS
      background: true
      description: This facilty allows for a form to be imported from an ALS file.
      link_text: "Import Form from ALS"
      link_path: "/imports/crfs/new?imports[file_type]=2"
    form_odm:
      title: Form Import - ODM
      background: true
      description: This facilty allows for a form to be imported from an ODM XML file.
      link_text: "Import Form from ODM"
      link_path: "/imports/crfs/new?imports[file_type]=1"
    term_excel:
      title: Import Terminology - EXCEL
      background: true
      description: This facilty allows for a form to be imported from an MS Excel file.
      link_text: "Import Terminology form Excel"
      link_path: "/imports/terms/new?imports[file_type]=0"
    term_odm:
      title: Import Terminology - ODM
      background: true
      description: This facilty allows for a form to be imported from an ODM XML file.
      link_text: "Import Terminology form ODM"
      link_path: "/imports/terms/new?imports[file_type]=1"
  processing:
    adam_ig:
      sheets: 
        main:
          label: Main
          columns: 
          - 
            label: "Data Structure Name"
            map:
              SUBJECT LEVEL ANALYSIS DATASET: Subject Level Analysis Dataset
              BASIC DATA STRUCTURE: Basic Data Structure
          - 
            label: "Dataset Name"
            map: []
          - 
            label: "Variable Group"
            map: []
          - 
            label: "Variable Name" 
            map: []
          - 
            label: "Variable Label"
            map: []
          - 
            label: "Type"
            map: 
              Char: Character
              Num: Numeric
          - 
            label: "Codelist/Controlled Terms"
            map: []
          - 
            label: "Core"
            map: 
              Req: Required
              Perm: Permissible
              Cond: Conditional
          - 
            label: "CDISC Notes"
            map: []

development:
  <<: *defaults

production: 
  <<: *defaults
  
test: 
  <<: *defaults
