defaults: &defaults
  imports: &default_imports
    cdisc_adam_ig: 
      title: CDISC ADaM IG Import - Excel
      background: true
      description: This facilty allows for the ADaM Implementation Guide to be imported from an MS Excel file.
      link_text: "Import CDISC ADaM IG"
      link_path: "/imports/adam_igs/new?imports[file_type]=0"
    cdisc_term: 
      title: CDISC Terminology Import - Excel
      background: true
      description: This facilty allows for the CDISC Terminology to be imported from an MS Excel file.
      link_text: "Import CDISC Term"
      link_path: "/imports/cdisc_terms/new?imports[file_type]=0"
    form_als:
      title: Form Import - ALS
      background: true
      description: This facilty allows for a form to be imported from an ALS file.
      link_text: "Import Form from ALS"
      link_path: "/imports/crfs/new?imports[file_type]=2"
    form_odm:
      title: Form Import - ODM
      background: true
      description: This facilty allows for a form to be imported from an ODM XML file.
      link_text: "Import Form from ODM"
      link_path: "/imports/crfs/new?imports[file_type]=1"
    term_excel:
      title: Import Terminology - EXCEL
      background: true
      description: This facilty allows for a form to be imported from an MS Excel file.
      link_text: "Import Terminology form Excel"
      link_path: "/imports/terms/new?imports[file_type]=0"
    term_odm:
      title: Import Terminology - ODM
      background: true
      description: This facilty allows for a form to be imported from an ODM XML file.
      link_text: "Import Terminology form ODM"
      link_path: "/imports/terms/new?imports[file_type]=1"
  processing: &default_processing
    cdisc_adam_ig: 
      sheets: 
        main:
          label: Main
          columns: 
          - 
            label: "Data Structure Name"
            actions:
              -
                method: create_parent
                object: parent
                klass: AdamIgDataset
                map:
                  SUBJECT LEVEL ANALYSIS DATASET: ADAMIG ADSL
                  BASIC DATA STRUCTURE: ADAMIG BDS
              -
                method: set_property
                object: parent
                property: label
                map:
                  SUBJECT LEVEL ANALYSIS DATASET: Subject Level Analysis Dataset
                  BASIC DATA STRUCTURE: Basic Data Structure
          - 
            label: "Dataset Name"
            actions: []
          - 
            label: "Variable Group"
            actions: []
          - 
            label: "Variable Name" 
            actions:
              -
                method: create_child
                object: child
                klass: AdamIgDataset::Variable
                map: {}
              -
                method: ordinal
                object: child
                property: ordinal
                map: {}
              -
                method: set_property
                object: child
                property: name
                map: {}
          - 
            label: "Variable Label"
            actions:
              -
                method: set_property
                object: child
                property: label
                map: {}
          - 
            label: "Type"
            actions:
              -
                method: datatype_classification
                object: child
                property: datatype
                map:
                  Char: Character
                  Num: Numeric
          - 
            label: "Codelist/Controlled Terms"
            actions:
              - 
                method: ct_reference
                object: child
                property: ct
                map: {}
              -
                method: ct_other
                object: child
                property: ct_notes
                map: {}
          - 
            label: "Core"
            actions:
              -
                method: core_classification
                object: child
                property: compliance
                map:
                  Req: Required
                  Perm: Permissible
                  Cond: Conditional
          - 
            label: "CDISC Notes"
            actions:
              -
                method: set_property
                object: child
                property: notes
                map: {}
    cdisc_term: 
      sheets: 
        main:
          label: Terminology
          columns: 
          - 
            label: "Code"
            actions:
              -
                method: c_code?
                object: NA
                klass: NA
                map: {}
              -
                method: create_parent
                object: parent
                klass: CdiscCl
                map: {}
                condition: 
                  method: column_blank?
                  column: 2
              -
                method: set_property
                object: parent
                property: identifier
                map: {}
                condition: 
                  method: column_blank?
                  column: 2
              -
                method: create_child
                object: child
                klass: CdiscCli
                map: {}
                condition: 
                  method: column_not_blank?
                  column: 2
              -
                method: set_property
                object: child
                property: identifier
                map: {}
                condition: 
                  method: column_not_blank?
                  column: 2
          - 
            label: "Codelist Code"
            actions: []
          - 
            label: "Codelist Extensible (Yes/No)"
            actions: 
              -
                method: set_property
                object: parent
                property: extensible
                map: 
                  "Yes": true
                  "No": false
                condition: 
                  method: column_blank?
                  column: 2
          - 
            label: "Codelist Name" 
            actions:
              -
                method: set_property
                object: parent
                property: label
                map: {}
                condition: 
                  method: column_blank?
                  column: 2
          - 
            label: "CDISC Submission Value"
            actions:
              -
                method: set_property
                object: parent
                property: notation
                map: {}
                condition: 
                  method: column_blank?
                  column: 2
              -
                method: set_property
                object: child
                property: notation
                map: {}
                condition: 
                  method: column_not_blank?
                  column: 2
          -
            label: "CDISC Synonym(s)"
            actions:
              -
                method: set_property
                object: parent
                property: synonym
                can_be_empty: true
                map: {}
                condition: 
                  method: column_blank?
                  column: 2
              -
                method: set_property
                object: child
                property: synonym
                can_be_empty: true
                map: {}
                condition: 
                  method: column_not_blank?
                  column: 2
          - 
            label: "CDISC Definition"
            actions:
              -
                method: set_property
                object: parent
                property: definition
                map: {}
                condition: 
                  method: column_blank?
                  column: 2
              -
                method: set_property
                object: child
                property: definition
                map: {}
                condition: 
                  method: column_not_blank?
                  column: 2
          - 
            label: "NCI Preferred Term"
            actions:
              -
                method: set_property
                object: parent
                property: preferredTerm
                map: {}
                condition: 
                  method: column_blank?
                  column: 2
              -
                method: set_property
                object: child
                property: preferredTerm
                map: {}
                condition: 
                  method: column_not_blank?
                  column: 2
              -
                method: set_property
                object: child
                property: label
                map: {}
                condition: 
                  method: column_not_blank?
                  column: 2

development:
  <<: *defaults

production: 
  <<: *defaults
  
test: 
  imports:
    <<: *default_imports
    test_1:
      title: Test 1 - Excel
      background: true
      description: A test
      link_text: "Import ADaM IG"
      link_path: "/imports/adam_igs/new?imports[file_type]=0"
    test_2:
      title: Test 2 - Excel
      background: true
      description: A test
      link_text: "Import ADaM IG"
      link_path: "/imports/adam_igs/new?imports[file_type]=0"
  processing:
    <<: *default_processing
    test_1:
      sheets: 
        sheet_1:
          label: Sheet1
          columns: 
          - 
            label: "PARENT"
            actions:
              -
                method: create_parent
                object: parent
                klass: ParentClass
                map:
                  P1: P1
                  P2: P2
              -
                method: set_property
                object: parent
                property: label
                map:
                  P1: Parent One
                  P2: Parent Two
          - 
            label: CHILD
            actions:
              -
                method: create_child
                object: child
                klass: ChildClass
                map: {}
              -
                method: ordinal
                object: child
                property: ordinal
                map: {}
              -
                method: set_property
                object: child
                property: label
                map: {}
          - 
            label: CT
            actions:
              - 
                method: ct_reference
                object: child
                property: ct
                map: {}
              -
                method: ct_other
                object: child
                property: ct_notes
                map: {}
          - 
            label: DATATYPE
            actions:
              -
                method: datatype_classification
                object: child
                property: datatype
                map:
                  CHAR: Character
                  NUM: Numeric
          - 
            label: CORE
            actions:
              -
                method: core_classification
                object: child
                property: compliance
                map:
                  R: Required
                  P: Permissible
                  E: Conditional
    test_2:
      sheets: 
        sheet_1:
          label: Sheet1
          columns: 
          - 
            label: "PARENT"
            actions:
              -
                method: create_parent
                object: parent
                klass: ParentClass
                map: {}
              -
                method: set_property
                object: parent
                property: label
                map:
                  P1: Parent One
                  P2: Parent Two
          - 
            label: CHILD
            actions:
              -
                method: create_child
                object: child
                klass: ChildClass
                map: {}
              -
                method: ordinal
                object: child
                property: ordinal
                map: {}
              -
                method: set_property
                object: child
                property: label
                map: {}
          - 
            label: CT
            actions:
              - 
                method: ct_reference
                object: child
                property: ct
                map: {}
              -
                method: ct_other
                object: child
                property: ct_notes
                map: {}
          - 
            label: DATATYPE
            actions:
              -
                method: datatype_classification
                object: child
                property: datatype
                map:
                  CHAR: Character
                  NUM: Numeric
          - 
            label: CORE
            actions:
              -
                method: core_classification
                object: child
                property: compliance
                map:
                  R: Required
                  P: Permissible
                  E: Conditional
    test_3:
      sheets: 
        sheet_1:
          label: hee # Note short name
          columns: 
          - 
            label: "PARENT"
            actions:
              -
                method: create_parent
                object: parent
                klass: ParentClass
                map:
                  P1: P1
                  P2: P2
              -
                method: set_property
                object: parent
                property: label
                map:
                  P1: Parent One
                  P2: Parent Two
          - 
            label: CHILD
            actions:
              -
                method: create_child
                object: child
                klass: ChildClass
                map: {}
              -
                method: ordinal
                object: child
                property: ordinal
                map: {}
              -
                method: set_property
                object: child
                property: label
                map: {}
          - 
            label: CT
            actions:
              - 
                method: ct_reference
                object: child
                property: ct
                map: {}
              -
                method: ct_other
                object: child
                property: ct_notes
                map: {}
                condition: 
                  method: column_blank?
                  column: 3
          - 
            label: DATATYPE
            actions:
              -
                method: datatype_classification
                object: child
                property: datatype
                map:
                  CHAR: Character
                  NUM: Numeric
          - 
            label: CORE
            actions:
              -
                method: core_classification
                object: child
                property: compliance
                map:
                  R: Required
                  P: Permissible
                  E: Conditional
