defaults: &defaults
  imports:
   -
    title: ADaM Model Import - Excel
    background: true
    route:
    description: This facilty allows for the ADaM Model to be imported from an MS Excel file.
    link_text: "Import ADaM Model"
    link_path: "/imports/adam_models/new?imports[file_type]=0"
   -
    title: ADaM IG Import - Excel
    background: true
    route:
    description: This facilty allows for the ADaM Implementation Guide to be imported from an MS Excel file.
    link_text: "Import ADaM IG"
    link_path: "/imports/adam_igs/new?imports[file_type]=0"
   -
    title: Form Import - ALS
    background: true
    route:
    description: This facilty allows for a form to be imported from an ALS file.
    link_text: "Import Form from ALS"
    link_path: "/imports/crfs/new?imports[file_type]=2"
   -
    title: Form Import - ODM
    background: true
    route:
    description: This facilty allows for a form to be imported from an ODM XML file.
    link_text: "Import Form from ODM"
    link_path: "/imports/crfs/new?imports[file_type]=1"
   -
    title: Import Terminology - EXCEL
    background: true
    route:
    description: This facilty allows for a form to be imported from an MS Excel file.
    link_text: "Import Terminology form Excel"
    link_path: "/imports/terms/new?imports[file_type]=0"
   -
    title: Import Terminology - ODM
    background: true
    route:
    description: This facilty allows for a form to be imported from an ODM XML file.
    link_text: "Import Terminology form ODM"
    link_path: "/imports/terms/new?imports[file_type]=1"

development:
  <<: *defaults

production: 
  <<: *defaults
  
test: 
  <<: *defaults
