defaults: &defaults
  GMAIL_DOMAIN: gmail.com
  GMAIL_USERNAME: glandon.development@gmail.com
  GMAIL_PASSWORD: Av23$or82*iaz

development:
  <<: *defaults
  xxxxx: yyyyyyy
  
production: 
  <<: *defaults
  
test: 
  <<: *defaults
