--- 
development: 
  dbType: "Ontotext"
  apiKey: s4h7h1e8absr
  secret: 47q8uce2r1b4cri
  queryEndpoint: "https://rdf.s4.ontotext.com/4830471037/Test/repositories/mdr"
  updateEndpoint: "https://rdf.s4.ontotext.com/4830471037/Test/repositories/mdr/statements"
  fileEndpoint: "https://rdf.s4.ontotext.com/4830471037/Test/repositories/mdr/statements"
production: 
  dbType: "Ontotext"
  apiKey: s4h7h1e8absr
  secret: 47q8uce2r1b4cri
  queryEndpoint: "https://rdf.s4.ontotext.com/4830471037/Test/repositories/mdr"
  updateEndpoint: "https://rdf.s4.ontotext.com/4830471037/Test/repositories/mdr/statements"
  fileEndpoint: "https://rdf.s4.ontotext.com/4830471037/Test/repositories/mdr/statements"
test: 
  dbType: "Ontotext"
  apiKey: s4h7h1e8absr
  secret: 47q8uce2r1b4cri
  queryEndpoint: "https://rdf.s4.ontotext.com/4830471037/Test/repositories/mdr"
  updateEndpoint: "https://rdf.s4.ontotext.com/4830471037/Test/repositories/mdr/statements"
  fileEndpoint: "https://rdf.s4.ontotext.com/4830471037/Test/repositories/mdr/statements"	