defaults: &defaults
  ApplicationPolicy:
    index:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: true
      curator: true
      content_admin: true
    show:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: true
      curator: true
      content_admin: true
    view:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: true
      curator: true
      content_admin: true
    all:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: true
      curator: true
      content_admin: true
    list:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: true
      curator: true
      content_admin: true
    history:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: true
      curator: true
      content_admin: true
    changes:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: true
      curator: true
      content_admin: true
    create:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    new:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    update:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    edit:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    clone:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    branch:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    upgrade:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    impact:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    import:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    destroy:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    export_json:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    export_xpt_metadata:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    export_ttl:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    export_csv:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
  AdHocReportPolicy:
    index:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    new:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    create:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    run_start:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    run_progress:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    run_results:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    results:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    show:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    destroy:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
  AuditTrailPolicy:
    index:
      sys_admin: true
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    search:
      sys_admin: true
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    export_csv:
      sys_admin: true
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
  BackgroundPolicy:
    index:
      sys_admin: true
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    destroy:
      sys_admin: true
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    destroy_multiple:
      sys_admin: true
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
  CdiscTermPolicy:
    index:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    show:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    view:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    import:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    history:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
  CdiscClPolicy:
    index:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    show:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    view:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
  CdiscCliPolicy:
    index:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    show:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    view:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
  DashboardPolicy:
    index:
      sys_admin: true
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    view:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    database:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    admin:
      sys_admin: true
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: false
  IsoManagedPolicy:
    index:
      sys_admin: false
      term_reader: false
      term_curator: true
      reader: false
      curator: true
      content_admin: true
    status:
      sys_admin: false
      term_reader: false
      term_curator: true
      reader: false
      curator: true
      content_admin: true
    export:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
  IsoNamesapcePolicy:
    index:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    show:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    create:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    new:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    update:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    edit:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    destroy:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
  IsoRegistrationAuthorityPolicy:
    index:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    show:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    create:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    new:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    update:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    edit:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    destroy:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
  IsoRegistrationStatePolicy:
    current:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    update:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
  IsoScopedIdentifierPolicy:
    update:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
  ThesaurusPolicy:
    index:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    show:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    view:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    history:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    create:
      sys_admin: false
      term_reader: false
      term_curator: true
      reader: false
      curator: true
      content_admin: true
    new:
      sys_admin: false
      term_reader: false
      term_curator: true
      reader: false
      curator: true
      content_admin: true
    edit:
      sys_admin: false
      term_reader: false
      term_curator: true
      reader: false
      curator: true
      content_admin: true
    impact:
      sys_admin: false
      term_reader: false
      term_curator: true
      reader: false
      curator: true
      content_admin: true
    destroy:
      sys_admin: false
      term_reader: false
      term_curator: true
      reader: false
      curator: true
      content_admin: true
    export_ttl:
      sys_admin: false
      term_reader: false
      term_curator: true
      reader: false
      curator: true
      content_admin: true
  ThesaurusConceptPolicy:
    index:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    show:
      sys_admin: false
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    create:
      sys_admin: false
      term_reader: false
      term_curator: true
      reader: false
      curator: true
      content_admin: true
    edit:
      sys_admin: false
      term_reader: false
      term_curator: true
      reader: false
      curator: true
      content_admin: true
    update:
      sys_admin: false
      term_reader: false
      term_curator: true
      reader: false
      curator: true
      content_admin: true
    destroy:
      sys_admin: false
      term_reader: false
      term_curator: true
      reader: false
      curator: true
      content_admin: true
  TokenPolicy:
    index:
      sys_admin: true
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    release:
      sys_admin: true
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    status:
      sys_admin: true
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
    extend_token:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: true
      content_admin: true
  UploadPolicy:
    index:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    create:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
  ImportPolicy:
    new:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    index:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    show:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    create:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    destroy:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    destroy_multiple:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    items:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    list:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
  ExportPolicy:
    index:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    start:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    terminologies:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    biomedical_concepts:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    forms:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
    download:
      sys_admin: false
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: true
  UserPolicy:
    index:
      sys_admin: true
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: false
    show:
      sys_admin: true
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: false
    new:
      sys_admin: true
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: false
    update:
      sys_admin: true
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: false
    update_name:
      sys_admin: true
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    create:
      sys_admin: true
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: false
    edit:
      sys_admin: true
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: false
    destroy:
      sys_admin: true
      term_reader: false
      term_curator: false
      reader: false
      curator: false
      content_admin: false
  UserSettingPolicy:
    index:
      sys_admin: true
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true
    update:
      sys_admin: true
      term_reader: true
      term_curator: true
      reader: true
      curator: true
      content_admin: true

development:
  <<: *defaults

production: 
  <<: *defaults
  
test: 
  <<: *defaults
