defaults: &defaults
  extensions:
    can_extend_unextensible: true 
  identifiers:
    scheme_type: flat # either :flat or :hierarchical. Can be symbol or string
    parent: 
      generated: 
        pattern: "NP[identifier]P" 
        width: "6"
    child: 
      generated: 
        pattern: "NC[identifier]C"
        width: "8"

development:
  <<: *defaults

production: 
  <<: *defaults
  
test: 
  <<: *defaults
