defaults: &defaults
  extensions:
    can_extend_unextensible: true 
  identifiers:
    scheme_type: flat # either :flat or :hierarchical. Can be symbol or string
    parent: 
      generated: 
        pattern: "H[identifier]" 
        width: "6"
    child: 
      generated: 
        pattern: "HI[identifier]"
        width: "6"

development:
  <<: *defaults

production: 
  <<: *defaults
  
test: 
  <<: *defaults
